### ISSUE TITLE
Failing to compile html5ever "Unsupported Erlang version"

### ISSUE THREAD

**Issue by sajoku** [Anonyfox/elixir-scrape#34]
I'm trying out elixir-scrape but ran into some issues. I resolved this by overriding the dependency html5ever inside `mix.exs`.
`html5ever` is failing to compile because of an unsupported version of Erlang. Setting html5ever dependency to the latest version released fixes this.

In mix.exs:
```elixir
defp deps do
      {:scrape, "~> 2.0"},
      {:html5ever, "~> 0.5.0", override: true}
    ]
  end
```
**Am I correct to assume that elixir-scrape should update it's dependencies?**

The error:
```elixir
==> rustler
Compiling 2 files (.erl)
Compiling 6 files (.ex)
warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1
  lib/rustler/toml_parser.ex:7

Generated rustler app
==> html5ever
Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
   Compiling erlang_nif-sys v0.5.4
   Compiling syntex_syntax v0.56.2
   Compiling html5ever-atoms v0.1.3
error: failed to run custom build command for `erlang_nif-sys v0.5.4`
process didn't exit successfully: `/Users/sajoku/code/dasher/_build/dev/rustler_crates/html5ever_nif/release/build/erlang_nif-sys-fc0a15601d7eef7f/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /Users/sajoku/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.5.4/build.rs:28:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
```

I'm on version: `Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]`

Also checkout the issue on html5ever_elixir: https://github.com/hansihe/html5ever_elixir/issues/7

**Comment by broeman** [comment]
I can reproduce the same problem and solution

**Comment by sajoku** [comment]
Thanks for checking and confirming that it works 🙂

**Comment by sajoku** [comment]
I haven't been working on this for a while but upon returning I ran into this issue  once again.
I probably was a bit eager in upgrading all the things and now html5ever is failing to build. 
This I fixed by cloning the [html5ever](https://hex.pm/packages/html5ever) repo locally and run the project with the following command `cargo rustc -- --codegen link-args='-flat_namespace -undefined suppress'`. The next step is referencing html5ever inside your own project with the following (if you're running a Phoenix-like app:

```elixir
{:html5ever, "~> 0.5.0", [override: true, path: "/code/html5ever_elixir"]},
```

**Comment by jacob-israel-turner** [comment]
I had a similar situation as @sajoku.  To solve, I cloned the html5ever repo locally and linked the dep like @sajoku did.  However, I did not end up needing to run the `cargo rustc` command.  Not sure why simply installing the dep locally would solve the issue here.

**Comment by aspin** [comment]
I'm still getting this, and none of the fixes proposed above work for me.
```
mix deps.compile
==> html5ever
Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
could not compile dependency :html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile html5ever", update it with "mix deps.update html5ever" or clean it with "mix deps.clean html5ever"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:622: System.cmd("cargo", ["rustc", "--no-default-features", "--release", "--", "--codegen", "link-args=-flat_namespace -undefined suppress"], [cd: "/Users/aspin/workspace/bearhalla/scripts/html5ever_elixir/native/html5ever_nif", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/Users/aspin/workspace/bearhalla/scripts/legend_img_downloader/_build/dev/rustler_crates/html5ever_nif"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    lib/mix/tasks/compile.rustler.ex:53: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
```

**Comment by sajoku** [comment]
What version(s) are you running @aspin ? I can try to repro with the same versions if possible.

**Comment by aspin** [comment]
I went around upgrading everything to try to figure this out so I'm a little unsure 😅 I do believe elixir 1.6.5, html5ever 0.5.0, scrape 2.0. I'm not sure what rust version, but I did a new install. Later I ended up downgrading scrape to the previous version and that compiled ok.

**Comment by sajoku** [comment]
@aspin I'm unable to reproduce unfortunately. 
You could try upgrading html5ever to the latest version and reference that in your project (or in scrape), since html5ever seems to be much further than version 0.5.0 https://github.com/servo/html5ever/releases

**Comment by Anonyfox** [comment]
the new release v3 does not depend on html5ever any more, so this issue should be gone
